export const boardConstants = {
    CREATE_REQUEST: 'BOARDS_CREATE_REQUEST',
    CREATE_SUCCESS: 'BOARDS_CREATE_SUCCESS',
    CREATE_FAILURE: 'BOARDS_CREATE_FAILURE',

    READ_REQUEST: 'BOARDS_READ_REQUEST',
    READ_SUCCESS: 'BOARDS_READ_SUCCESS',
    READ_FAILURE: 'BOARDS_READ_FAILURE',

    UDPATE_REQUEST: 'BOARDS_UDPATE_REQUEST',
    UPDATE_SUCCESS: 'BOARDS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'BOARDS_UPDATE_FAILURE',

    DELETE_REQUEST: 'BOARDS_DELETE_REQUEST',
    DELETE_SUCCESS: 'BOARDS_DELETE_SUCCESS',
    DELETE_FAILURE: 'BOARDS_DELETE_FAILURE',
};